'use client';
import {useEffect,useRef,useState,useContext,createContext,type FormEvent} from 'react';
import type {SkillSummary,SkillComparison,AssessmentSchedule} from '@/lib/assessment';
type Screen='home'|'question'|'break'|'win'|'parent'|'bests'|'me';
type PublicItem={id:string;skillId:string;subject:'maths'|'english';kind:'number'|'choice'|'spelling'|'reading';yearLevel:number;prompt:string;choices?:string[];passage?:string};
type Question={assessmentId:string;sessionId:string;part:string;kind:string;item?:PublicItem;sessionEnded:boolean;sessionDeadline?:string;assessmentComplete?:boolean;feedback?:string;brainBreak?:boolean};
type State={configured:boolean;signedIn:boolean;hasPin?:boolean;voiceConfigured:boolean;curriculumVerified:boolean;baselineComplete?:boolean;baselineStarted?:boolean;schedule?:AssessmentSchedule};
type Recording={passage?:string;description?:string;id:string;item_id:string;assessment_id:string;accuracy_estimate:number|null;parent_accuracy:number|null;created_at:string;expires_at:string};
type Review={description:string;item_id:string;assessment_id:string;parent_accuracy:number;original_estimate:number|null;created_at:string};
type Report={reviews:Review[];curriculumVerified:boolean;baseline?:{completed_at:string|null;started_at:string};later?:{completed_at:string|null};schedule:AssessmentSchedule;skills:{id:string;description:string;yearLevel:number;subject:string}[];baselineSummary:SkillSummary[];laterSummary:SkillSummary[];comparison:SkillComparison[];recordings:Recording[];sessions:{id:string;part:string;status:string;started_at:string;completed_at:string|null}[];estimatedSpendCents:number;budgetCents:number;guessCount:number};
const feedback:Record<string,string>={good:'You gave that a go. Nice effort.',try:'We can practise that one later.',rush:'Whoa, speedy! Let’s read that one again together.',skip:'Thanks for telling me. We can try that another time.'};
const BusyContext=createContext(false);
const speakerIcon=<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m11 4-6 5H2v6h3l6 5V4Zm4 4c2 2 2 6 0 8m3-11c4 4 4 10 0 14"/></svg>;
function Speaker({onClick,label='Hear this',disabled=false}:{onClick:()=>void;label?:string;disabled?:boolean}){const contextBusy=useContext(BusyContext);return <button type="button" className="speaker" aria-label={label} onClick={onClick} disabled={disabled||contextBusy}>{speakerIcon}</button>;}
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again with Mum.');return result as T;}
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleDateString('en-AU',{timeZone:'Australia/Perth',day:'numeric',month:'short',year:'numeric'}):'Not started';
const level:Record<string,string>={unassessed:'Not checked yet',needs_practice:'Not yet',developing:'Getting there',provisional_strength:'Early strength — still checking',secure:'Secure'};
// Reuse one audio element: iPhone audio is primed synchronously by a tap, before any network request.
const silentWav='data:audio/wav;base64,UklGRiYAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQIAAAAAAA==';
export default function LearningLab(){
 const [screen,setScreen]=useState<Screen>('home'),[state,setState]=useState<State|null>(null),[question,setQuestion]=useState<Question|null>(null),[answer,setAnswer]=useState(''),[assisted,setAssisted]=useState(false),[hint,setHint]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[caption,setCaption]=useState(''),[word,setWord]=useState(-1),[audioReady,setAudioReady]=useState(false),[report,setReport]=useState<Report|null>(null),[pin,setPin]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[recording,setRecording]=useState(false),[clip,setClip]=useState<Blob|null>(null),[recordingUrl,setRecordingUrl]=useState(''),[subject,setSubject]=useState('all');
 const audio=useRef<HTMLAudioElement|null>(null),audioUrl=useRef(''),readyAt=useRef(0),captionRef=useRef(''),media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recordStart=useRef(0),recordDuration=useRef(0),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null),activeOperation=useRef(0),audioDone=useRef<(()=>void)|null>(null),heading=useRef<HTMLHeadingElement|null>(null);
 async function refresh(){try{setState(await request<State>('/api/state'));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();return ()=>{activeOperation.current++;stream.current?.getTracks().forEach(track=>track.stop());if(recordTimer.current)clearTimeout(recordTimer.current);if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);};},[]);
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo(0,0);},[screen]);
 useEffect(()=>{if(!question?.sessionDeadline||!['question','break'].includes(screen))return;const timer=setTimeout(()=>{void stop();},Math.max(0,Date.parse(question.sessionDeadline)-Date.now()));return ()=>clearTimeout(timer);},[question?.sessionDeadline,screen]);
 useEffect(()=>()=>{if(recordingUrl)URL.revokeObjectURL(recordingUrl);},[recordingUrl]);
 function prime(){const element=audio.current;if(element){element.src=silentWav;void element.play().catch(()=>{});}}
 function stopAudio(){activeOperation.current++;audio.current?.pause();audioDone.current?.();audioDone.current=null;setWord(-1);}
 async function say(line:string,text:string,q=question){
  audio.current?.pause();audioDone.current?.();audioDone.current=null;const operation=++activeOperation.current;setCaption(text);captionRef.current=text;setWord(-1);if(line==='item')setAudioReady(false);
  const response=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({line,...(line==='item'&&q?.item?{sessionId:q.sessionId,itemId:q.item.id}:{})})});
  if(!response.ok){const result=await response.json();throw new Error(result.error||'Ask Mum to help with the sound.');}
  const blob=await response.blob();if(operation!==activeOperation.current)return;
  if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current=URL.createObjectURL(blob);
  const element=audio.current;if(!element)return;element.src=audioUrl.current;
  await new Promise<void>((resolve,reject)=>{audioDone.current=resolve;element.onended=()=>{audioDone.current=null;if(operation===activeOperation.current){setWord(-1);if(line==='item'){setAudioReady(true);if(!readyAt.current)readyAt.current=performance.now();}}resolve();};element.onerror=()=>reject(new Error('Tap the speaker to try the sound again.'));element.play().catch(()=>reject(new Error('Tap the speaker to start the sound.')));});
 }
 async function replay(line:string,text:string){prime();setError('');setBusy(true);try{await say(line,text);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function words(text:string){return text.split(/\s+/).map((token,index)=><span key={index} className={index===word&&caption===text?'spoken-word':''}>{token} </span>);}
 async function showQuestion(q:Question){
  setQuestion(q);readyAt.current=0;setAnswer('');setHint(false);setAssisted(false);setClip(null);setRecordingUrl('');setError('');
  if(q.sessionEnded){setScreen('win');await say('win','One last little win. Can you tap your friendly gecko?',q);void refresh();return;}
  setScreen('question');setAudioReady(false);
  if(q.item){await say('item',q.item.kind==='spelling'?'Listen to the word and its sentence. Then type the word.':q.item.prompt,q);}
 }
 async function begin(){prime();setError('');if(!state?.signedIn||!state.hasPin){setScreen('parent');return;}if(!state.curriculumVerified){setScreen('parent');setError('The SCSA curriculum sources still need verification before Summer starts.');return;}setBusy(true);try{await say('hello','Hi, Summer! I’m your computer voice. Small steps. Let’s give it a gecko!');const q=await request<Question>('/api/assessment',{action:'start'});await showQuestion(q);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(event?:FormEvent,skip=false){event?.preventDefault();if(!question?.item||!audioReady||(!answer.trim()&&!skip))return;setBusy(true);setError('');try{const q=await request<Question>('/api/answer',{sessionId:question.sessionId,itemId:question.item.id,answer:skip?'':answer,responseMs:Math.round(performance.now()-readyAt.current),assisted});setQuestion(q);setAnswer('');setHint(false);setAssisted(false);setAudioReady(false);try{await say(q.feedback||'good',feedback[q.feedback||'good']);}catch{/* A saved answer must still advance when feedback audio fails. */}if(q.brainBreak&&!q.sessionEnded){setQuestion(q);setScreen('break');await say('break','Do your best goanna walk. Tap when you’re ready.');}else await showQuestion(q);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function stop(){stopAudio();if(recordTimer.current)clearTimeout(recordTimer.current);if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setClip(null);setRecordingUrl('');setBusy(true);setError('');try{if(question?.sessionId)await request('/api/assessment',{action:'stop',sessionId:question.sessionId});setQuestion(null);setScreen('home');setCaption('Good stopping. We can come back when you’re ready.');void refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function hintPlease(){setHint(true);setAssisted(true);await replay('hint','Take your time. Think about the first little step. Mum can help.');}
 async function startRecording(){prime();setError('');setBusy(true);setClip(null);setRecordingUrl('');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('Ask Mum to open this app in Safari or Chrome using its secure web address.');setBusy(false);return;}try{
  stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime){stream.current.getTracks().forEach(t=>t.stop());throw new Error('This browser cannot record this reading. Try Safari or Chrome.');}
  const recorder=new MediaRecorder(stream.current,{mimeType:mime}),chunks:BlobPart[]=[];media.current=recorder;
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{recordDuration.current=Math.min(65000,performance.now()-recordStart.current);const blob=new Blob(chunks,{type:mime});setClip(blob);setRecordingUrl(URL.createObjectURL(blob));setRecording(false);stream.current?.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);};
  recordStart.current=performance.now();recorder.start();setRecording(true);recordTimer.current=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},60000);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setError((e as Error).name==='NotAllowedError'?'The microphone is off. Ask Mum to allow it, then tap again.':(e as Error).message);}finally{setBusy(false);}}
 async function sendReading(){if(!clip||!question?.item)return;setBusy(true);setError('');try{const form=new FormData();form.set('audio',clip,'reading');form.set('sessionId',question.sessionId);form.set('itemId',question.item.id);form.set('durationMs',String(Math.round(recordDuration.current)));form.set('assisted',String(assisted));const response=await fetch('/api/reading',{method:'POST',body:form});const q=await response.json();if(!response.ok)throw new Error(q.error);setQuestion(q);setClip(null);setRecordingUrl('');setAudioReady(false);try{await say('good','Thanks for reading. Mum can listen to your little story later.');}catch{/* The reading is saved; continue to its next instruction. */}await showQuestion(q);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function signIn(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await request('/api/auth',{email,password});setPassword('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function unlock(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await request('/api/parent',{action:state?.hasPin?'unlock':'setPin',pin});setPin('');await refresh();setReport(await request<Report>('/api/parent'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function listenRecording(id:string){setError('');try{const response=await fetch(`/api/parent?recording=${id}`);if(!response.ok)throw new Error('Unlock the parent area again, or check whether this recording has expired.');const blob=await response.blob();if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current=URL.createObjectURL(blob);if(audio.current){audio.current.onended=()=>{};audio.current.src=audioUrl.current;await audio.current.play();}}catch(e){setError((e as Error).message);}}
 async function correctRecording(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');try{await request('/api/parent',{action:'correctReading',recordingId:id,accuracy:Number(form.get('accuracy'))});setReport(await request<Report>('/api/parent'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function go(next:Screen){if(question?.sessionId&&['question','break'].includes(screen)&&next!=='parent'){setError('Tap Stop for today first. Your tries will be saved.');return;}stopAudio();setReport(null);setError('');setScreen(next);}
 const item=question?.item;
 return <BusyContext.Provider value={busy||recording}><audio ref={audio} preload="auto" onTimeUpdate={()=>{const player=audio.current;if(player&&Number.isFinite(player.duration)&&player.duration>0&&item?.kind!=='spelling')setWord(Math.min(captionRef.current.split(/\s+/).length-1,Math.floor(player.currentTime/player.duration*captionRef.current.split(/\s+/).length)));}}/>
 <div className="phase-note">Phase 1 · Warm-up build · {state?.configured?'Private family app':'Mum: service connections still needed'}</div>
 <div className="lab-shell"><header className="lab-header"><button className="brand" onClick={()=>void go('home')}><span className="brand-tile"><img src="/assets/star.png" alt=""/></span><span>Summer’s<br/><strong>Learning Lab</strong></span></button><button className="speaker" aria-label="Parent area" disabled={busy||recording} onClick={()=>{stopAudio();setError('');setScreen('parent');setReport(null);}}><svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/></svg></button></header>
 {error&&<div className="error-message" role="alert">{error}</div>}
 {busy&&<p className="busy-note" role="status">One little moment…</p>}
 <main>
 {screen==='home'&&<section><div className="home-panel card"><div className="home-copy"><div className="read-row"><h1 ref={heading} tabIndex={-1}>Hi, Summer!</h1><Speaker onClick={()=>void replay('home','Hi, Summer! Small steps. Lots of little wins. Tap Let’s go when you’re ready.')} label="Hear the home screen"/></div><p>Small steps. Lots of little wins.</p><div className="home-cta"><button className="primary" onClick={()=>void begin()} disabled={busy}>Let’s go <span>→</span></button><Speaker onClick={()=>void replay('start','Let’s try a few little questions. There is no rush. You can stop when you need a break.')} label="Hear the warm-up instructions"/></div></div><div className="mascot-orbit"><img src="/assets/lizard.png" alt="Your friendly gecko sidekick"/><span className="bubble">Let’s give it<br/>a gecko!</span></div></div><div className="home-status card"><img src="/assets/books.png" alt="" width="48" height="48"/><p>{state?.baselineComplete?'Nice trying! Mum can see your warm-up results.':'Our first adventure: a little warm-up challenge.'}</p><Speaker onClick={()=>void replay('start','Let’s try a few little questions. There is no rush.')} /></div>{state?.baselineComplete&&<p className="parent-note">Daily learning comes in Phase 2. The four-week check will follow four weeks of learning.</p>}</section>}
 {screen==='question'&&item&&<section className="warmup"><div className="lesson-bar"><p>{question.part==='maths'?'A little maths':question.part==='reading'?'A little reading':'A little word magic'}</p><button className="secondary" disabled={busy} onClick={()=>void stop()}>Stop for today</button></div><div className="card question-panel"><div className="read-row"><h1 ref={heading} tabIndex={-1}>{item.kind==='spelling'?'Listen. Then spell.':item.kind==='reading'?'Your little story':words(item.prompt)}</h1><Speaker label={item.kind==='spelling'?'Hear the spelling word and sentence':'Hear the question'} onClick={()=>void replay('item',item.kind==='spelling'?'Listen to the word and its sentence. Then type the word.':item.prompt)} disabled={busy||recording}/></div>
 {item.kind==='reading'?<><p className="reading-instruction">Read this little story aloud.</p><div className="passage">{item.passage}</div><p className="mic-note">Mum can help with the microphone. Tap Allow when your phone asks.</p><Speaker label="Hear microphone instructions" onClick={()=>void replay('recording','Tap the microphone, then read the little story. Tap stop when you’re done.')} disabled={recording}/>{recording?<button className="primary" onClick={()=>media.current?.stop()}>Stop recording</button>:<button className="primary" disabled={busy||!audioReady} onClick={()=>void startRecording()}>{clip?'Record again':'Start recording'}</button>}{clip&&<div className="recorded-preview"><audio src={recordingUrl} controls aria-label="Listen to this reading before sending"/><button className="primary" disabled={busy} onClick={()=>void sendReading()}>Save my reading →</button></div>}</>:<form onSubmit={submit}>{item.kind==='spelling'&&<p>Listen again whenever you like.</p>}{item.choices?<div className="choices">{item.choices.map(choice=><button type="button" key={choice} className={`choice ${answer===choice?'selected':''}`} disabled={!audioReady||busy} onClick={()=>setAnswer(choice)} aria-pressed={answer===choice}>{choice}</button>)}</div>:<><label htmlFor="answer">Your answer</label><input id="answer" value={answer} onChange={e=>setAnswer(e.target.value)} inputMode={item.kind==='number'?'decimal':'text'} autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={160} disabled={!audioReady||busy} /></>}<button className="primary" disabled={busy||!answer.trim()||!audioReady}>Have a go →</button></form>}
 <button className="skip-button" onClick={()=>void submit(undefined,true)} disabled={busy||recording||!audioReady}>I’m not sure yet</button><div className="hint-row"><button className="hint-button" onClick={()=>void hintPlease()} disabled={busy||recording}><img src="/assets/lightbulb.png" alt="" width="32" height="32"/>A little hint, please</button><Speaker onClick={()=>void replay('replay','You can tap the speaker to hear those words again.')} label="Hear the speaker instruction"/></div>{hint&&<div className="hint-card"><img src="/assets/lizard.png" alt="" width="55" height="55"/><p>Think about the first little step. Mum can help.</p><Speaker onClick={()=>void replay('hint','Take your time. Think about the first little step. Mum can help.')}/></div>}
 </div><div className="gentle-row"><p>No rush. We can try together.</p><Speaker onClick={()=>void replay('start','There is no rush. You can stop when you need a break.')}/></div></section>}
 {screen==='break'&&<section className="centre-card card"><img className="large-gecko" src="/assets/lizard.png" alt="A gecko ready for a silly walk"/><h1 ref={heading} tabIndex={-1}>A silly brain break</h1><p>Do your best goanna walk!</p><Speaker onClick={()=>void replay('break','Do your best goanna walk. Tap when you’re ready.')}/><button className="primary" disabled={busy} onClick={()=>{prime();setBusy(true);void showQuestion(question!).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Ready for another go →</button><button className="secondary" onClick={()=>void stop()}>Stop for today</button></section>}
 {screen==='win'&&<section className="centre-card card"><h1 ref={heading} tabIndex={-1}>One last little win</h1><p>Can you tap your friendly gecko?</p><Speaker onClick={()=>void replay('win','One last little win. Can you tap your friendly gecko?')}/><button className="gecko-win" aria-label="Tap the gecko" disabled={busy} onClick={()=>{prime();setBusy(true);void say('finish','You did some good trying today! What do you call a lizard that sings? A rap-tile!').catch(e=>setError(e.message)).finally(()=>{setBusy(false);setQuestion(null);setScreen('home');void refresh();});}}><img src="/assets/lizard.png" alt=""/></button><p>Your tries are saved.</p></section>}
 {screen==='bests'&&<section className="centre-card card"><img src="/assets/trophy.png" alt="" width="100" height="100"/><h1 ref={heading} tabIndex={-1}>My personal bests</h1><p>Your little wins will go here.<br/>First, let’s try our warm-up.</p><Speaker onClick={()=>void replay('start','First, let’s try a little warm-up challenge. There is no rush.')}/><button className="primary" onClick={()=>void begin()} disabled={busy}>Let’s go →</button></section>}
 {screen==='me'&&<section className="centre-card card"><img className="large-gecko" src="/assets/lizard.png" alt="Your sample reptile sidekick"/><h1 ref={heading} tabIndex={-1}>My little sidekick</h1><p>Choosing your reptile comes next.</p><Speaker onClick={()=>void replay('hello','Hi, Summer! I’m your computer voice. Small steps. Let’s give it a gecko!')}/><button className="primary" onClick={()=>void go('home')}>Back home →</button></section>}
 {screen==='parent'&&<section className="parent-screen"><h1 ref={heading} tabIndex={-1}>For Mum</h1>{!state?.configured?<div className="card setup-panel"><h2>Connect the family app</h2><p>The code is built, but the private database and voice are not connected in this environment yet.</p><ol><li>In Supabase, run the supplied database setup in SQL Editor.</li><li>Add your project URL, publishable key and parent email in environment settings.</li><li>Enter your OpenAI key securely as SUMMER_OPENAI_KEY.</li><li>Create your parent sign-in in Supabase, then return here.</li></ol><p>The curriculum map is still a draft awaiting official source verification. Summer’s warm-up will stay closed until that check is complete.</p></div>:!state.signedIn?<form className="card parent-form" onSubmit={signIn}><h2>Parent sign-in</h2><label htmlFor="email">Your email</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/><label htmlFor="password">Password</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button className="primary" disabled={busy}>Sign in</button><p>Only the parent account configured for this family can sign in.</p></form>:!report?<form className="card parent-form" onSubmit={unlock}><h2>{state.hasPin?'Unlock the parent area':'Choose your parent PIN'}</h2><label htmlFor="pin">Six-digit PIN</label><input id="pin" type="password" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value)} autoComplete="off" required/><button className="primary" disabled={busy}>{state.hasPin?'Unlock':'Save PIN'}</button><p>The parent area locks again after ten minutes. Five wrong PIN attempts pause access for ten minutes.</p></form>:<>
 <div className="card summary-card"><h2>Summer’s starting point</h2><p>Baseline: {date(report.baseline?.completed_at)}. Follow-up: {date(report.later?.completed_at)}.</p><p>{report.schedule.dueAt?`Four-week check due ${date(report.schedule.dueAt)}. ${report.schedule.learningSessions} learning sessions recorded.`:'The four-week clock starts with her first normal learning session in Phase 2.'}</p><p>{report.curriculumVerified?'Curriculum sources checked.':'Curriculum mapping is a draft and still needs official SCSA verification.'}</p><p>{report.guessCount} likely guesses, treated as rechecks rather than confirmed gaps.</p><p>Voice spending reservation this UTC month: US${(report.estimatedSpendCents/100).toFixed(2)} of US${(report.budgetCents/100).toFixed(2)}. This is a conservative app estimate, not your OpenAI invoice.</p></div>
 <div className="card summary-card"><h2>Skill-by-skill progress</h2><p>These are early observations. Unchecked skills stay unassessed. A secure skill needs strong results across at least three learning sessions.</p><label htmlFor="subject-filter">Show subject</label><select id="subject-filter" value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">Both subjects</option><option value="maths">Maths</option><option value="english">English</option></select><div className="skill-list">{report.skills.filter(s=>subject==='all'||s.subject===subject).map(s=>{const before=report.baselineSummary.find(x=>x.skillId===s.id),after=report.laterSummary.find(x=>x.skillId===s.id),change=report.comparison.find(x=>x.skillId===s.id);return <article key={s.id} className="skill-row"><h3>{s.description}</h3><p>{s.yearLevel===0?'Pre-primary':`Year ${s.yearLevel}`} · {s.subject==='maths'?'Maths':'English'}</p><p>Starting point: {level[before?.status||'unassessed']} · confidence: {before?.confidence||'none'}</p>{before&&before.independentAttempts>0&&<p>Independent answers: {before.correct} of {before.independentAttempts}. Helped answers: {before.assistedAttempts}. Likely guesses: {before.likelyGuessAttempts}.</p>}{report.later&&<p>Later: {level[after?.status||'unassessed']} · confidence: {after?.confidence||'none'}</p>}{change?.levels.map((l,i)=><p key={i}>Matched questions: {l.baseline.correct}/{l.baseline.total} before; {l.followup.correct}/{l.followup.total} later. {l.confidence} confidence.</p>)}</article>;})}</div></div>
 <div className="card summary-card"><h2>Reading recordings</h2><p>Speech recognition may turn what Summer said into what it thinks she meant. Scores are estimates, not reliable reading grades. Listen and add your own score. Recordings become inaccessible after 30 days and are deleted by the scheduled job; review corrections stay saved.</p>{!report.recordings.length&&<p>No current recordings.</p>}{report.recordings.map(r=><article key={r.id} className="recording-row"><h3>{r.description||'Reading observation'}</h3><p>{date(r.created_at)} · deletes {date(r.expires_at)}</p>{r.passage&&<blockquote>{r.passage}</blockquote>}<p>Computer estimate: {r.accuracy_estimate===null?'Unavailable':`${r.accuracy_estimate}%`}. Your review: {r.parent_accuracy===null?'Not reviewed':`${r.parent_accuracy}%`}.</p><button className="secondary" onClick={()=>void listenRecording(r.id)}>Listen to recording</button><form onSubmit={e=>void correctRecording(e,r.id)}><label htmlFor={`score-${r.id}`}>Your accuracy score (%)</label><input id={`score-${r.id}`} name="accuracy" type="number" min="0" max="100" step="1" defaultValue={r.parent_accuracy??''} required/><button className="secondary" disabled={busy}>Save my review</button></form></article>)}</div>
 <div className="card summary-card"><h2>Saved reading reviews</h2><p>Your reviews stay here when the audio expires. The original warm-up record stays unchanged.</p>{report.reviews.length?report.reviews.map((r,i)=><p key={i}>{date(r.created_at)} · {r.description} · your review: {r.parent_accuracy}% · original computer estimate: {r.original_estimate===null?'Unavailable':`${r.original_estimate}%`}</p>):<p>No parent reviews yet.</p>}</div><div className="card summary-card"><h2>Warm-up sessions</h2>{report.sessions.length?report.sessions.map(s=><p key={s.id}>{date(s.started_at)} · {s.part} · {s.status==='stopped'?'Stopped early':s.status==='completed'?'Finished':'In progress'} · {s.completed_at?`${Math.max(1,Math.round((Date.parse(s.completed_at)-Date.parse(s.started_at))/60000))} minutes`:'Not finished yet'}</p>):<p>No sessions yet.</p>}</div>
 </>}{state?.signedIn&&<button className="secondary" onClick={()=>{setBusy(true);void request('/api/auth',{action:'signout'}).then(()=>{setReport(null);return refresh();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Sign out</button>}</section>}
 {caption&&screen!=='parent'&&<div className="voice-caption" aria-live="polite"><p>{item?.kind==='spelling'?caption:words(caption)}</p></div>}
 </main></div>
 <div className="nav-wrap"><nav className="bottom-nav" aria-label="Summer’s menu">{([['home','⌂','Home'],['question','▤','Learn'],['bests','☆','Beat My Score'],['me','☺','Me']] as const).map(([target,icon,label])=><button key={target} aria-current={screen===target?'page':undefined} onClick={()=>target==='question'?void begin():void go(target)} disabled={busy||recording}><span aria-hidden="true">{icon}</span>{label}</button>)}<Speaker label="Hear the menu" onClick={()=>void replay('menu','Home. Learn. Beat My Score. Me.')} disabled={recording}/></nav></div>
 </BusyContext.Provider>;
}
