'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,BookOpen,Check} from 'lucide-react';
import {chooseVoice,naturalVoices,preferredVoice,type NaturalVoice} from '@/lib/natural-voice';
import config from '@/lib/config/natural-voice.json';
export default function VoiceCheck(){
 const [selected,setSelected]=useState<NaturalVoice>('coral'),[message,setMessage]=useState('');
 const players=useRef<(HTMLAudioElement|null)[]>([]);
 useEffect(()=>{setSelected(preferredVoice());return ()=>players.current.forEach(audio=>audio?.pause());},[]);
 function choose(voice:NaturalVoice){try{chooseVoice(voice);setSelected(voice);setMessage('Voice saved. Your tutor will use it on this device.');}catch(error){setMessage(error instanceof Error?error.message:'Please try again.');}}
 return <main className="lab-shell screen-welcome"><header className="lab-header"><Link className="brand" href="/"><span className="brand-tile"><BookOpen size={24}/></span><span><strong>Summer’s Learning Lab</strong><br/>Maths and English</span></Link></header><section><div className="page-intro"><h1><span className="title-line">Find your</span><span className="title-italic">tutor’s voice</span></h1><p>Listen to three AI voices, then choose your favourite. The same voice will speak your tutor’s replies.</p><p>Each voice has been directed to speak warmly with an Australian accent. Listen for the sound you prefer.</p></div><div className="section-grid">{naturalVoices.map((voice,index)=><article className="card summary-card" key={voice}><h2>{voice[0].toUpperCase()+voice.slice(1)}</h2><p>The same short introduction, so you can compare.</p><audio ref={node=>{players.current[index]=node;}} controls preload="metadata" style={{width:'100%'}} src={`/audio/${config.revision}/${voice}-preview.mp3`} aria-label={`Listen to ${voice}`} onPlay={()=>players.current.forEach((audio,i)=>{if(i!==index)audio?.pause();})}/><button className={selected===voice?'secondary':'primary'} aria-pressed={selected===voice} onClick={()=>choose(voice)}>{selected===voice?<><Check size={20}/>Selected</>:'Use this voice'}</button></article>)}</div><p role="status" style={{marginTop:24}}>{message}</p><p className="support-note">The voice is generated by AI. New replies are created as you talk; you can read them while the sound starts.</p><Link className="secondary" href="/" style={{marginTop:24}}><ArrowLeft size={19}/>Back to lessons</Link></section></main>;
}
